[workspace.metadata.dylint]
libraries = [
  { path = "/ABSOLUTE/PATH/TO/rust-perf-norm/machine-oriented-lints" },
]

[machine_oriented_lints]
small_vec_capacity_threshold = 64
vec_new_then_push_min_pushes = 2
